import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { HvmGeneratedModule, HvmGeneratedSharedModule } from './generated/module';
import { HvmValidator, registerValidationChecks } from './hvm-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type HvmAddedServices = {
    validation: {
        HvmValidator: HvmValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type HvmServices = LangiumServices & HvmAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const HvmModule: Module<HvmServices, PartialLangiumServices & HvmAddedServices> = {
    validation: {
        HvmValidator: () => new HvmValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createHvmServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Hvm: HvmServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        HvmGeneratedSharedModule
    );
    const Hvm = inject(
        createDefaultModule({ shared }),
        HvmGeneratedModule,
        HvmModule
    );
    shared.ServiceRegistry.register(Hvm);
    registerValidationChecks(Hvm);
    return { shared, Hvm };
}
